[workspace]
resolver = "2"
members = ["terrain_and_stuff", "xtask"]
default-members = ["terrain_and_stuff"]

[patch.crates-io]
wgpu = { git = "https://github.com/wumpf/wgpu", branch = "better-webgpu-selection2" }
wgpu-types = { git = "https://github.com/wumpf/wgpu", branch = "better-webgpu-selection2" }
naga = { git = "https://github.com/wumpf/wgpu", branch = "better-webgpu-selection2" }
wgpu-hal = { git = "https://github.com/wumpf/wgpu", branch = "better-webgpu-selection2" }

#minifb = { path = "../rust_minifb" }
